"""add CharacterWeaponLink model

Revision ID: fbf132ffca64
Revises: bb98f6a6d8b6
Create Date: 2023-08-02 15:50:16.977993

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'fbf132ffca64'
down_revision = 'bb98f6a6d8b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characterweaponlink',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('weapon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['weapon_id'], ['weapon.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'weapon_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characterweaponlink')
    # ### end Alembic commands ###
